### ISSUE TITLE
Any link redirects to the main domain of YunoHost

### ISSUE THREAD

**Issue by theRAGEhero** [YunoHost-Apps/yourls_ynh#20]
Hello,
I've tried to install YOURLS v 1.8.1  on  YunoHost 4.2.5.3 (stable) but on every link I click it redirects me to the my main YunoHost domain.
Anyone could help me?
Thank you

**Comment by anmol26s** [comment]
Can you show the php logs?

**Comment by theRAGEhero** [comment]
Sorry I didn't have access to a laptop.

I did more trials, if I setup Yourls on domain.com/yourls it redirects me to the main domain of YunoHost.

Now I'm using a subdomain, go.domain.com and what it happens is that it redirects me to a blank page with written. `File not found`.

` /var/log/php7.3-fpm.log  `

```
[24-Sep-2021 19:58:23] NOTICE: systemd monitor interval set to 10000ms
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yourls.yourls_options' doesn't exist in /var/www/yourls/includes/vendor/aura/sql/src/AbstractExtendedPdo.php:558"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "Stack trace:"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#0 /var/www/yourls/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(558): PDOStatement->execute()"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#1 /var/www/yourls/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(412): Aura\Sql\AbstractExtendedPdo->perform('SELECT option_v...', Array)"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#2 /var/www/yourls/includes/Database/Options.php(110): Aura\Sql\AbstractExtendedPdo->fetchOne('SELECT option_v...', Array)"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#3 /var/www/yourls/includes/functions-options.php(25): YOURLS\Database\Options->get('version', false)"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#4 /var/www/yourls/includes/functions.php(478): yourls_get_option('version')"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#5 /var/www/yourls/includes/functions.php(460): yourls_get_current_version_from_sql()"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#6 /var/www/yourls/includes/Config/Init.php(95): yourls_upgrade_is_needed()"
[24-Sep-2021 19:58:32] WARNING: [pool yourls] child 31197 said into stderr: "#7 /var/www/yourls/includes/load-yourls.php(26): YOURLS\Config..."
[24-Sep-2021 19:58:51] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful

```

ps. I've also seen that there is a new version of Yourls (not yet for YunoHost).
